#!/bin/sh
DEVICE_NAME=`cat /proc/sys/kernel/hostname`;
MACFILE="/etc/known_mac";

ID="WIREPUSHER_ID";

TITLE="Mew%20device%20found!";
MESSAGE="New%20device%20found!%20Router%20name:%20DEVICE_NAME,%20MAC:%20MAC_ADDR;%20IP:%20IP_ADDR;%20Hostname:%20HOST_NAME"
TYPE="new_device";

REQUEST_URI="http://wirepusher.com/send?id=$ID&title=$TITLE&message=_MESSAGE_&type=$TYPE";

while true; do
    cat /tmp/dhcp.leases | cut -d" " -f2 | 
        while read i; 
            do grep "$i" -i "$MACFILE" > /dev/null 2>&1; 
                if [ $? -eq 0 ]; 
                    then 
                        echo "$i is known"; 
                    else
                        IP=`cat /proc/net/arp | grep "$i" | cut -d" " -f1`;
                        HOSTNAME=`cat /tmp/dhcp.leases | grep "$IP" | cut -d" " -f4`;
                        echo "$i $IP $HOSTNAME" >> "$MACFILE";
                        CURRENT_MESSAGE=`echo $MESSAGE | sed "s/DEVICE_NAME/$DEVICE_NAME/g" | sed "s/MAC_ADDR/$i/g" | sed "s/IP_ADDR/$IP/g" | sed "s/HOST_NAME/$HOSTNAME/g"`;
                        URI=`echo -n $REQUEST_URI | sed "s/_MESSAGE_/$CURRENT_MESSAGE/g"`; 
                        echo "Mac $i is not known! Addind to known list and sending push notification. IP: $IP; HOSTNAME: $HOSTNAME";
                        curl $URI >/dev/null 2>&1;
                fi;
            done;
    sleep 60;
done;
