#!/bin/sh
DEVICE_NAME=`cat /proc/sys/kernel/hostname`;
MACFILE="/etc/known_mac";

ID="WIREPUSHER_ID";

TITLE="New device found!";
MESSAGE="New device found! Router name: DEVICE_NAME, MAC: MAC_ADDR; IP: IP_ADDR; Hostname: HOST_NAME"
TYPE="new_device";

MTITLE=`echo $TITLE | sed "s/ /%20/g"`
REQUEST_URI="http://wirepusher.com/send?id=$ID&title=$MTITLE&message=_MESSAGE_&type=$TYPE";

while true; do
        MACS=`cat /tmp/dhcp.leases | sed "s/\*/NO_NAME/g" | sed "s/$/@#@#@#@#/g"`;
        echo $MACS | sed "s/@#@#@#@# /\r\n/g" | cut -d" " -f2 | 
        while read i; 
            do grep "$i" -i "$MACFILE" > /dev/null 2>&1; 
                if [ $? -eq 0 ]; 
                    then 
                        echo "$i is known"; 
                    else
                        IP=`echo $MACS | sed "s/@#@#@#@# /\r\n/g" | grep "$i"  | cut -d" " -f3`;
                        HOSTNAME=`echo $MACS | sed "s/@#@#@#@# /\r\n/g" | grep "$i" | cut -d" " -f4`;
                        echo "$i $IP $HOSTNAME" >> "$MACFILE";
                        CURRENT_MESSAGE=`echo $MESSAGE | sed "s/ /%20/g"  | sed "s/DEVICE_NAME/$DEVICE_NAME/g" | sed "s/MAC_ADDR/$i/g" | sed "s/IP_ADDR/$IP/g" | sed "s/HOST_NAME/$HOSTNAME/g"`;
                        URI=`echo -n $REQUEST_URI | sed "s/_MESSAGE_/$CURRENT_MESSAGE/g"`; 
                        echo "Mac $i is not known! Addind to known list and sending push notification. IP: $IP; HOSTNAME: $HOSTNAME";
                        curl $URI >/dev/null 2>&1;
                fi;
            done;
    sleep 60;
done;
 
